// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from './application';
import TwoFactorAwareSignInController from './two_factor_aware_sign_in';

application.register(
  'two-factor-aware-sign-in',
  TwoFactorAwareSignInController
);
